### ISSUE TITLE
PHP Notice:  Undefined index: implicit in /../w/includes/user/UserGroupManager.php on line 267

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#144]
### Setup

- MediaWiki | 1.35.0-rc.2 (37ef236)17:21, 22 August 2020
- PHP | 7.2.24-0ubuntu0.18.04.6 (apache2handler)
- MariaDB | 10.1.44-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (127a703) 14:33, 22 August 2020
- Semantic Extra Special Properties | 2.1.0 (01a45e4) 12:33, 9 February 2020

### Issue
Caused by `'_USERGROUP'` being part of the array of special properties defined with `$sespgEnabledPropertyList` after the upgrade of the wiki from MW 1.34 to MW 1.35. Issued when rebuilding data with the "rebuildData.php" script. The user groups are still stored as expected.

```
[1d77ad5f0a5dc252b7ea83f2] [no req]   TypeError from line 267 of /../w/includes/user/UserGroupManager.php: Return value of MediaWiki\User\UserGroupManager::getUserImplicitGroups() must be of the type array, null returned
```

### Backtrace
```
#0 /../w/includes/user/UserGroupManager.php(295): MediaWiki\User\UserGroupManager->getUserImplicitGroups(User, integer, boolean)
#1 /../w/includes/user/User.php(2911): MediaWiki\User\UserGroupManager->getUserEffectiveGroups(User, integer, boolean)
#2 /../w/includes/Permissions/PermissionManager.php(1295): User->getEffectiveGroups()
#3 /../w/includes/user/User.php(2866): MediaWiki\Permissions\PermissionManager->getUserPermissions(User)
#4 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageContributorsPropertyAnnotator.php(82): User->getRights()
#5 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageContributorsPropertyAnnotator.php(69): SESP\PropertyAnnotators\PageContributorsPropertyAnnotator->isNotAnonymous(User)
#6 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/DispatchingPropertyAnnotator.php(73): SESP\PropertyAnnotators\PageContributorsPropertyAnnotator->addAnnotation(SMW\DIProperty, SMW\SemanticData)
#7 /../w/extensions/SemanticExtraSpecialProperties/src/ExtraPropertyAnnotator.php(72): SESP\PropertyAnnotators\DispatchingPropertyAnnotator->addAnnotation(SMW\DIProperty, SMW\SemanticData)
#8 /../w/extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(176): SESP\ExtraPropertyAnnotator->addAnnotation(SMW\SemanticData)
#9 /../w/includes/HookContainer/HookContainer.php(320): SESP\HookRegistry->SESP\{closure}(SMW\Elastic\ElasticStore, SMW\SemanticData)
#10 /../w/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#11 /../w/includes/Hooks.php(137): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#12 /../w/extensions/SemanticMediaWiki/src/Store.php(230): Hooks::run(string, array)
#13 /../w/extensions/SemanticMediaWiki/src/Store.php(271): SMW\Store->updateData(SMW\SemanticData)
#14 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(98): SMW\Store->clearData(SMW\DIWikiPage)
#15 /../w/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(239): SMW\MediaWiki\Jobs\UpdateJob->run()
#16 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(466): SMW\SQLStore\Rebuilder\Rebuilder->rebuild(integer)
#17 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(383): SMW\Maintenance\DataRebuilder->doUpdateById(integer)
#18 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(222): SMW\Maintenance\DataRebuilder->rebuildAll()
#19 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#20 /../w/maintenance/doMaintenance.php(107): SMW\Maintenance\rebuildData->execute()
#21 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#22 {main}
```

**Comment by kghbln** [comment]
This issue however causes "rebuildElasticIndex.php" to fail:

```
PHP Notice:  Undefined index: implicit in /../w/includes/user/UserGroupManager.php on line 267

Notice: Undefined index: implicit in /../w/includes/user/UserGroupManager.php on line 267
[c3841f82bfdf00dd3c60186d] [no req]   TypeError from line 267 of /../w/includes/user/UserGroupManager.php: Return value of MediaWiki\User\UserGroupManager::getUserImplicitGroups() must be of the type array, null returned
```

**Backtrace:**
```
#0 /../w/includes/user/UserGroupManager.php(295): MediaWiki\User\UserGroupManager->getUserImplicitGroups(User, integer, boolean)
#1 /../w/includes/user/User.php(2911): MediaWiki\User\UserGroupManager->getUserEffectiveGroups(User, integer, boolean)
#2 /../w/includes/Permissions/PermissionManager.php(1295): User->getEffectiveGroups()
#3 /../w/includes/user/User.php(2866): MediaWiki\Permissions\PermissionManager->getUserPermissions(User)
#4 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageContributorsPropertyAnnotator.php(82): User->getRights()
#5 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageContributorsPropertyAnnotator.php(69): SESP\PropertyAnnotators\PageContributorsPropertyAnnotator->isNotAnonymous(User)
#6 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/DispatchingPropertyAnnotator.php(73): SESP\PropertyAnnotators\PageContributorsPropertyAnnotator->addAnnotation(SMW\DIProperty, SMW\SQLStore\EntityStore\StubSemanticData)
#7 /../w/extensions/SemanticExtraSpecialProperties/src/ExtraPropertyAnnotator.php(72): SESP\PropertyAnnotators\DispatchingPropertyAnnotator->addAnnotation(SMW\DIProperty, SMW\SQLStore\EntityStore\StubSemanticData)
#8 /../w/extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(176): SESP\ExtraPropertyAnnotator->addAnnotation(SMW\SQLStore\EntityStore\StubSemanticData)
#9 /../w/includes/HookContainer/HookContainer.php(320): SESP\HookRegistry->SESP\{closure}(SMW\SQLStore\SQLStore, SMW\SQLStore\EntityStore\StubSemanticData)
#10 /../w/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#11 /../w/includes/Hooks.php(137): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#12 /../w/extensions/SemanticMediaWiki/src/Store.php(230): Hooks::run(string, array)
#13 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Attachment/FileAttachment.php(177): SMW\Store->updateData(SMW\SQLStore\EntityStore\StubSemanticData)
#14 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(348): SMW\Elastic\Indexer\Attachment\FileAttachment->SMW\Elastic\Indexer\Attachment\{closure}()
#15 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(246): SMW\MediaWiki\Deferred\CallableUpdate->runUpdate()
#16 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/TransactionalCallableUpdate.php(168): SMW\MediaWiki\Deferred\CallableUpdate->doUpdate()
#17 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(284): SMW\MediaWiki\Deferred\TransactionalCallableUpdate->doUpdate()
#18 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Attachment/FileAttachment.php(186): SMW\MediaWiki\Deferred\CallableUpdate->pushUpdate()
#19 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/FileIndexer.php(312): SMW\Elastic\Indexer\Attachment\FileAttachment->createAttachment(SMW\DIWikiPage)
#20 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder/Rebuilder.php(322): SMW\Elastic\Indexer\FileIndexer->index(SMW\DIWikiPage)
#21 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(482): SMW\Elastic\Indexer\Rebuilder\Rebuilder->rebuild(string, SMW\SQLStore\EntityStore\StubSemanticData)
#22 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(419): SMW\Maintenance\rebuildElasticIndex->rebuildFromRow(integer, integer, stdClass, string)
#23 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(186): SMW\Maintenance\rebuildElasticIndex->rebuild()
#24 /../w/maintenance/doMaintenance.php(107): SMW\Maintenance\rebuildElasticIndex->execute()
#25 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(552): require_once(string)
#26 {main}
```

**Comment by thomas-topway-it** [comment]
Hello, any progress with this issue ? This prevents us from upgrading from Mediawiki 1.34 to 1.35 with a smw with Semantic Extra Special Properties
thanks

**Comment by gesinn-it** [comment]
I fixed Travis to get a better overview: https://travis-ci.org/github/SemanticMediaWiki/SemanticExtraSpecialProperties/builds/758666315

I think SESP / CI needs some more love, e.g. pinning CI to specific SMW vesions, not latest master

**Comment by thomas-topway-it** [comment]
@gesinn-it
thanks for checking,
I'm not sure I understand, our configuration is the following (below), shall I use some other versions ? (or a different combination of them?)

Semantic Extra Special Properties	2.1.0
Semantic MediaWiki	3.2.2
Semantic Result Formats	3.2.0

MediaWiki	1.35.1
PHP	7.4.15 (fpm-fcgi)

**Comment by gesinn-it** [comment]
To say which versions are "production ready", Travis CI and test coverage should be fixed.

**Comment by thomas-topway-it** [comment]
so I have empirically solved this just using
```
		if(isset($this->userGroupCache[$userKey][self::CACHE_IMPLICIT])) {
				return $this->userGroupCache[$userKey][self::CACHE_IMPLICIT];
		} else {
			return $groups;
		}
```
in the function ``getUserImplicitGroups`` in the file ``includes/user/UserGroupManager.php`` and the same for the function ``getUserEffectiveGroups`` in the same file.

However, that does not solve my issue (which I don't know whether it is related or not to the issue of this thread) that is, after executing php maintenance/runJobs.php (perhaps there were many old jobs never accomplished) for some reason the category is not anymore indexed by smw, even after ``php maintenance/rebuildall.php`` and ``php extensions/SemanticMediaWiki/maintenance/rebuildData.php``
as pointed out by Karsten
this is an example page 
https://culturaitaliana.org/wiki/Special:Browse?title=Special%3ABrowse&article=Istituto+cultura+italiana+%28NGO%29%2FArticles%2FBorders+and+frontiers%2C+the+past%2C+the+present+and+the+future%3A+comparative+history+and+international+relations+between+Italy+and+Georgia
where the category should be present and it's not.
This causes inline ask queries with a category among the conditions to fail and return an empty result

**Comment by krabina** [comment]
can confirm the issue in this environment (after upgrading from MW 1.31):

MediaWiki | 1.35.3
-- | --
PHP | 7.3.29 (fpm-fcgi)
MariaDB | 10.3.31-MariaDB
ICU | 50.2
Semantic Extra Special Properties | 2.1.0 (01a45e4) 12:33, 9. Feb. 2020
Semantic MediaWiki | 3.2.3 (5619c2d) 00:40, 30. Mär. 2021


```
... updating 1048      [T: SMW/Schema:Group:Predefined_properties]
[5744b956cb29cbc10887ac62] [no req]   TypeError from line 267 of /includes/user/UserGroupManager.php: Return value of MediaWiki\User\UserGroupManager::getUserImplicitGroups() must be of the type array, null returned
Backtrace:
#0 /includes/user/UserGroupManager.php(295): MediaWiki\User\UserGroupManager->getUserImplicitGroups(User, integer, boolean)
#1 /includes/user/User.php(2972): MediaWiki\User\UserGroupManager->getUserEffectiveGroups(User, integer, boolean)
#2 /includes/Permissions/PermissionManager.php(1295): User->getEffectiveGroups()
#3 /includes/user/User.php(2927): MediaWiki\Permissions\PermissionManager->getUserPermissions(User)
#4 /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageContributorsPropertyAnnotator.php(82): User->getRights()
#5 /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageContributorsPropertyAnnotator.php(69): SESP\PropertyAnnotators\PageContributorsPropertyAnnotator->isNotAnonymous(User)
#6 /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/DispatchingPropertyAnnotator.php(73): SESP\PropertyAnnotators\PageContributorsPropertyAnnotator->addAnnotation(SMW\DIProperty, SMW\SemanticData)
#7 /extensions/SemanticExtraSpecialProperties/src/ExtraPropertyAnnotator.php(72): SESP\PropertyAnnotators\DispatchingPropertyAnnotator->addAnnotation(SMW\DIProperty, SMW\SemanticData)
#8 /extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(176): SESP\ExtraPropertyAnnotator->addAnnotation(SMW\SemanticData)
#9 /includes/HookContainer/HookContainer.php(329): SESP\HookRegistry->SESP\{closure}(SMW\SQLStore\SQLStore, SMW\SemanticData)
#10 /includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#11 /includes/Hooks.php(137): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#12 /extensions/SemanticMediaWiki/src/Store.php(230): Hooks::run(string, array)
#13 /extensions/SemanticMediaWiki/src/Store.php(271): SMW\Store->updateData(SMW\SemanticData)
#14 /extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(98): SMW\Store->clearData(SMW\DIWikiPage)
#15 /extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(239): SMW\MediaWiki\Jobs\UpdateJob->run()
#16 /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(466): SMW\SQLStore\Rebuilder\Rebuilder->rebuild(integer)
#17 /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(383): SMW\Maintenance\DataRebuilder->doUpdateById(integer)
#18 /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(222): SMW\Maintenance\DataRebuilder->rebuildAll()
#19 /extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#20 /maintenance/doMaintenance.php(107): SMW\Maintenance\rebuildData->execute()
#21 /extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#22 {main}


```

**Comment by kghbln** [comment]
A duplicate issue was created with https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/156 and subsequently fixed with https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/pull/176

**Comment by marijnvanwezel** [comment]
We came across this issue with version 3.0.4 of SESP.
